version: '2'

volumes:
  multibinder:
  rendered-data:

services:

  multibinder:
    image: "multibinder"
    container_name: 'multibinder'
    mem_limit: '128m'
    network_mode: host
    restart: always
    ports:
      - "80"
      - "443"
    volumes:
      - "multibinder:/run"

  haproxy:
    image: "haproxy"
    container_name: 'haproxy'
    network_mode: host
    mem_limit: '128m'
    restart: always
    volumes:
      - "multibinder:/run"
      - "rendered-data:/usr/local/etc"
      - "/dev/log:/dev/log:ro"
      - "/tmp:/var/run/haproxy:rw"
    environment:
      - 'SERVICE_IGNORE=true'
      - 'CONFIG=/usr/local/etc/haproxy/haproxy.cfg.erb'

  consul:
    image: "consul:0.7.5"
    container_name: 'consul'
    mem_limit: '32m'
    restart: always
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "53:53"
      - "53:53/udp"
    environment:
      - 'SERVICE_IGNORE=true'
    #command: "agent -server -rejoin -bootstrap -client=0.0.0.0 -bind=127.0.0.1 -advertise=127.0.0.1"
    command: "agent -server -rejoin -bootstrap -client=0.0.0.0 -advertise=127.0.0.1"

  registrator:
    image: "gliderlabs/registrator:v7"
    container_name: 'registrator'
    mem_limit: '32m'
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    command: "-resync 120 -ip 127.0.0.1 consul://consul:8500"
    #command: "-resync 120 -internal consul://consul:8500"
    links:
      - consul:consul
    depends_on:
      - consul

  consul-template:
    image: "avthart/consul-template"
    container_name: 'consul-template'
    mem_limit: '32m'
    restart: always
    environment:
      - 'CONSUL_TEMPLATE_LOG=info'
    #command: '-consul=consul:8500 -config /etc/consul/consul-template.conf -template "/etc/consul/template.d/haproxy.ctml:/usr/local/etc/haproxy/haproxy.cfg.erb:docker restart haproxy"'
    command: '-consul=consul:8500 -config /etc/consul/consul-template.conf -template "/etc/consul/template.d/haproxy.ctml:/usr/local/etc/haproxy/haproxy.cfg.erb:docker exec -t haproxy /usr/local/bin/multibinder-haproxy-wrapper /usr/sbin/haproxy -Ds -f $CONFIG -p /var/run/haproxy-site.pid"'
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "rendered-data:/usr/local/etc"
      - "/opt/docker/consul/consul-template.conf:/etc/consul/consul-template.conf:ro"
      - "/opt/docker/consul/template.d/haproxy.ctml:/etc/consul/template.d/haproxy.ctml:ro"
    links:
      - consul:consul
    depends_on:
      - consul
